stages:
  - deploy

image: alpine:3.17.3

variables:
  TAG: "${CI_COMMIT_TAG}"

################   COMMON CI SCRIPTS   ################

.prepare_env:
  before_script:
    - set -x
    - export TAG="${TAG}"
    - export "YC_TOKEN=${YC_TOKEN}"
    - export "YC_CLOUD_ID=${YC_CLOUD_ID}"
    - export "YC_FOLDER_ID=${YC_FOLDER_ID}"
    - export "S3_KEY_ID=${S3_KEY_ID}"
    - export "S3_SECRET=${S3_SECRET}"
    - export "SSH_PUB_KEY=${SSH_PUB_KEY}"
    - export "NEXUS_REPO_USER=${NEXUS_REPO_USER}"
    - export "NEXUS_REPO_PASS=${NEXUS_REPO_PASS}"
    - export "NEXUS_HELM_REPO=${NEXUS_HELM_REPO}"
    - mkdir ~/.ssh
    - cp $SSH_PRIV_KEY ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod -R +x scripts/* application/scripts/*
    - scripts/env.sh

.deploy-momo:
  script:
    - cd application
    - scripts/deploy.sh

################   MAIN CI JOBS   ################

deploy momo:
  stage: deploy
  when: manual
  extends:
    - .prepare_env
    - .deploy-momo
  only:
    - tags
