stages:
  - test
  - upload
  - build
  - scan

include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
  TAG: "${CI_COMMIT_TAG}"
  VERSION: "${TAG}"

sonarqube-sast:
  stage: test
  allow_failure: true
  image:
    name: gitlab.praktikum-services.ru:5050/zerodistance/momo-store/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - cd frontend
    - >
      sonar-scanner
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_FRONT}
      -Dsonar.sources=.
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_FRONT}

build_code:
  image: gitlab.praktikum-services.ru:5050/zerodistance/momo-store/node:16.20.0-alpine3.17
  stage: upload
  script:
    - cd frontend
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - frontend/dist

upload_nexus:
  stage: upload
  script:
    - cd frontend
    - tar czf momo-store-frontend-${TAG}.tar.gz dist
    - >       
      curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file momo-store-frontend-${TAG}.tar.gz ${NEXUS_REPO_FRONT_URL}/momo-store-frontend/${TAG}/momo-store-frontend-${TAG}.tar.gz
  only:
    - tags
  needs:
    - build_code

build_&_push_image:
  stage: build
  image: gitlab.praktikum-services.ru:5050/zerodistance/momo-store/docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - docker build -t $CI_REGISTRY_IMAGE/momo-store-frontend:${TAG} .
    - docker push $CI_REGISTRY_IMAGE/momo-store-frontend:${TAG}
  only:
    - tags

image_scan:
  needs: 
    - job: build_&_push_image
  stage: scan
  image: 
    name: gitlab.praktikum-services.ru:5050/zerodistance/momo-store/docker:20.10.12-dind-rootless
  services:
    - docker:dind
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - set -x
    - cd frontend
    - docker run --rm -e TRIVY_USERNAME=$CI_REGISTRY_USER -e TRIVY_PASSWORD=$CI_REGISTRY_PASSWORD
      gitlab.praktikum-services.ru:5050/zerodistance/momo-store/trivy:latest
      image --scanners vuln --severity HIGH,CRITICAL --no-progress
      $CI_REGISTRY_IMAGE/momo-store-frontend:${TAG} > frontend-scan-report.txt
  artifacts:
    expire_in: 1 hour
    paths:
      - backend/frontend-scan-report.txt
  only:
    - tags
