stages:
  - test
  - upload
  - build
  - scan

include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

sonarqube-sast:
  stage: test
  image:
    name: gitlab.praktikum-services.ru:5050/zerodistance/momo-store/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - cd frontend
    - >
      sonar-scanner
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_FRONT}
      -Dsonar.sources=.
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_FRONT}

build_code:
  image: gitlab.praktikum-services.ru:5050/zerodistance/momo-store/node:16.20.0-alpine3.17
  stage: upload
  script:
    - cd frontend
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - frontend/dist

upload_nexus:
  stage: upload
  script:
    - cd frontend
    - tar czf momo-store-frontend-${VERSION}.tar.gz dist
    - >       
      curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file momo-store-frontend-${VERSION}.tar.gz ${NEXUS_REPO_FRONT_URL}/momo-store-frontend/${VERSION}/momo-store-frontend-${VERSION}.tar.gz
  only:
    changes:
      - frontend/*
  needs:
    - build_code

build_&_push_image:
  when: manual
  stage: build
  image: gitlab.praktikum-services.ru:5050/zerodistance/momo-store/docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - docker build -t $CI_REGISTRY_IMAGE/momo-store-frontend:${VERSION} .
    - docker push $CI_REGISTRY_IMAGE/momo-store-frontend:${VERSION}

security_scan:
  needs: 
    - job: build_&_push_image
  stage: scan
  image: 
    name: gitlab.praktikum-services.ru:5050/zerodistance/momo-store/docker:20.10.12-dind-rootless
  services:
    - docker:dind
  before_script:
    - until docker info; do sleep 1; done
  script:
    - set -x
    - cd frontend
    - docker run --rm -e TRIVY_USERNAME=$CI_REGISTRY_USER -e TRIVY_PASSWORD=$CI_REGISTRY_PASSWORD
      gitlab.praktikum-services.ru:5050/zerodistance/momo-store/trivy:latest
      -q image --scanners vuln --severity HIGH,CRITICAL --output backend-scan-report.txt --no-progress
      $CI_REGISTRY_IMAGE/momo-store-frontend:${VERSION} > frontend-scan-report.txt
  artifacts:
    expire_in: 1 hour
    paths:
      - backend/frontend-scan-report.txt
