image: alpine:3.17.3

stages:
  - create
  - deploy
  - destroy

variables:
  TAG: "${CI_COMMIT_TAG}"
#  VERSION: "${TAG}"
  VERSION: "v1.0.5"

################   COMMON CI SCRIPTS   ################

.prepare_env:
  before_script:
    - set -x
    - export VERSION="${VERSION}"
    - export "YC_TOKEN=${YC_TOKEN}"
    - export "YC_CLOUD_ID=${YC_CLOUD_ID}"
    - export "YC_FOLDER_ID=${YC_FOLDER_ID}"
    - export "S3_KEY_ID=${S3_KEY_ID}"
    - export "S3_SECRET=${S3_SECRET}"
    - export "SSH_PUB_KEY=${SSH_PUB_KEY}"
    - export "NEXUS_REPO_USER=${NEXUS_REPO_USER}"
    - export "NEXUS_REPO_PASS=${NEXUS_REPO_PASS}"
    - export "NEXUS_HELM_REPO=${NEXUS_HELM_REPO}"
    - mkdir ~/.ssh
    - cp $SSH_PRIV_KEY ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod -R +x scripts/* terraform/scripts/*
    - scripts/env.sh

.cluster-create:
  script:
    - set -x
    - cd terraform
    - scripts/prepare.sh
    - terraform init -backend-config=backend.conf
    - terraform validate && terraform plan
    - scripts/create.sh apply -auto-approve
    - terraform apply -refresh-only -auto-approve
    - terraform state list
  artifacts:
    expire_in: 1 hour
    paths:
      - terraform/terraform.log 

.momo-deploy:
  script:
    - cd terraform
    - scripts/deploy.sh

.cluster-destroy:
  script:
    - set -x
    - cd terraform
    - scripts/prepare.sh
    - terraform init -backend-config=backend.conf
    - terraform validate && terraform destroy -auto-approve
    - terraform state list

################   MAIN CI JOBS   ################

create cluster:
  stage: create
  when: manual
  extends:
    - .prepare_env
    - .cluster-create

deploy momo:
  stage: deploy
  when: manual
  extends:
    - .prepare_env
    - .momo-deploy
#  only:
#    - tags

destroy cluster:
  stage: destroy
  when: manual
  extends:
    - .prepare_env
    - .cluster-destroy
