image: alpine:3.17.3

stages:
  - create
  - destroy

######  common configs  ######

.prepare_env:
  before_script:
    - set -x
    - export "S3_KEY_ID=${S3_KEY_ID}"
    - export "S3_SECRET=${S3_SECRET}"
    - export "SSH_PUB_KEY=${SSH_PUB_KEY}"
    - export "YC_TOKEN=${YC_TOKEN}"
    - mkdir ~/.ssh
    - cp $SSH_PRIV_KEY ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod -R +x scripts/* terraform/scripts/*
    - scripts/env.sh

.cluster-deploy:
  script:
    - set -x
    - cd terraform
    - scripts/prepare.sh
    - terraform init -backend-config=backend.conf
    - terraform validate && terraform plan
    - scripts/deploy.sh apply -auto-approve
    - terraform apply -refresh-only -auto-approve
    - terraform state list
  artifacts:
    expire_in: 1 hour
    paths:
      - terraform/terraform.log 

.app-deploy:
  after_script:
    - cd terraform
    - scripts/helm.sh

.cluster-destroy:
  script:
    - set -x
    - cd terraform
    - scripts/prepare.sh
    - terraform init -backend-config=backend.conf
    - terraform validate && terraform destroy -auto-approve
    - terraform state list

######  main jobs  ######

create cluster:
  stage: create
  when: manual
  extends:
    - .prepare_env
    - .cluster-deploy
    - .app-deploy

destroy cluster:
  stage: destroy
  when: manual
  extends:
    - .prepare_env
    - .cluster-destroy
