{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    - hosts:
        - {{ .Values.ingress.fqdn | quote }}
      secretName: momo-tls
  rules:
    - host: {{ .Values.ingress.fqdn | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}
              port:
                number: {{ .Values.ingress.port }}
{{- end }}
