environment: production 

replicaCount: 1
revisionHistoryLimit: 5
image: gitlab.praktikum-services.ru:5050/zerodistance/momo-store/momo-store-frontend

imagePullPolicy: IfNotPresent

imagePullSecrets:
  - name: docker-registry

updateStrategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

annotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"

service:
  name: frontend
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  fqdn: momo.sirius.online
  port: 80

