stages:
  - create
  - deploy
  - destroy

image: alpine:3.17.3

variables:
  TAG: "${CI_COMMIT_TAG}"

################   COMMON CI SCRIPTS   ################

.prepare_env:
  before_script:
    - set -x
    - export TAG="${TAG}"
    - export VERSION="${VERSION}"
    - export "YC_TOKEN=${YC_TOKEN}"
    - export "YC_CLOUD_ID=${YC_CLOUD_ID}"
    - export "YC_FOLDER_ID=${YC_FOLDER_ID}"
    - export "S3_KEY_ID=${S3_KEY_ID}"
    - export "S3_SECRET=${S3_SECRET}"
    - export "SSH_PUB_KEY=${SSH_PUB_KEY}"
    - export "NEXUS_REPO_USER=${NEXUS_REPO_USER}"
    - export "NEXUS_REPO_PASS=${NEXUS_REPO_PASS}"
    - export "NEXUS_HELM_REPO=${NEXUS_HELM_REPO}"
    - mkdir ~/.ssh
    - cp $SSH_PRIV_KEY ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod -R +x scripts/* infrastructure/scripts/*
    - scripts/env.sh

.create-cluster:
  script:
    - cd infrastructure
    - scripts/prepare.sh
    - terraform init -backend-config=backend.conf
    - terraform validate && terraform plan
    - terraform apply -auto-approve
    - terraform apply -refresh-only -auto-approve
    - terraform state list 

.deploy-soft:
  script:
    - cd infrastructure
    - scripts/deploy.sh

.destroy-cluster:
  script:
    - cd infrastructure
    - scripts/prepare.sh
    - terraform init -backend-config=backend.conf
    - terraform validate && terraform destroy -auto-approve
    - terraform state list

################   MAIN CI JOBS   ################

create cluster:
  stage: create
  when: manual
  extends:
    - .prepare_env
    - .create-cluster

deploy soft:
  stage: deploy
  when: manual
  extends:
    - .prepare_env
    - .deploy-soft

destroy cluster:
  stage: destroy
  when: manual
  extends:
    - .prepare_env
    - .destroy-cluster
