---
apiVersion: v2
type: application
name: momo-store
description: Momo Store Helm Chart

#version: v1.0.1
#appVersion: "1.0.1"

dependencies:
  - name: momo-store-backend
    version: 1.0.1
  - name: momo-store-frontend
    version: 1.0.1
