apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
    env: "{{ .Values.environment }}"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}:{{ .Values.global.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: frontend
              containerPort: 8080
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: frontend.conf
              readOnly: true
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: frontend.conf
                path: frontend.conf

