stages:
  - upload

image: alpine:3.17.3

variables:
  TAG: "${CI_COMMIT_TAG}"
  VERSION: "${TAG}"
  CHART_VERSION: "${TAG}"

helm upload:
  stage: upload
  when: manual
  before_script:
    - set -x
    - chmod -R +x scripts/*
    - scripts/prepare.sh
  script:
    - cd helm
    - helm version
    - helm package momo-store/
    - curl -u "${NEXUS_REPO_USER}":"${NEXUS_REPO_PASS}" "${NEXUS_HELM_REPO}"
      --upload-file momo-store-"${CHART_VERSION}".tgz
  only:
    - tags
