stages:
  - upload

image: alpine:3.17.3

variables:
  TAG: "${CI_COMMIT_TAG}"
  VERSION: 1.0.${CI_PIPELINE_ID}
#  VERSION: "v1.0.13"

################   COMMON CI SCRIPTS   ################

.prepare_env:
  before_script:
    - set -x
    - export TAG="${TAG}"
    - export VERSION="${VERSION}"
    - export "SSH_PUB_KEY=${SSH_PUB_KEY}"
    - export "NEXUS_REPO_USER=${NEXUS_REPO_USER}"
    - export "NEXUS_REPO_PASS=${NEXUS_REPO_PASS}"
    - export "NEXUS_HELM_REPO=${NEXUS_HELM_REPO}"
    - mkdir ~/.ssh
    - cp $SSH_PRIV_KEY ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod -R +x scripts/*
    - scripts/env.sh

.upload_momo-store:
  script:
    - cd packages
    - helm version
    - helm package momo-store/ --version "${TAG}" --app-version "${TAG}"
    - curl -u "${NEXUS_REPO_USER}":"${NEXUS_REPO_PASS}" "${NEXUS_HELM_REPO}"
      --upload-file momo-store-"${TAG}".tgz

.upload_monitoring-tools:
  script:
    - cd packages
    - helm version
    - helm package monitoring-tools/ --version "${VERSION}" --app-version "${VERSION}"
    - curl -u "${NEXUS_REPO_USER}":"${NEXUS_REPO_PASS}" "${NEXUS_HELM_REPO}"
      --upload-file monitoring-tools-"${VERSION}".tgz

.upload_cert-manager:
  script:
    - cd packages
    - helm version
    - helm package cert-manager/ --version "${VERSION}" --app-version "${VERSION}"
    - curl -u "${NEXUS_REPO_USER}":"${NEXUS_REPO_PASS}" "${NEXUS_HELM_REPO}"
      --upload-file cert-manager-"${VERSION}".tgz

.upload_ingress-nginx:
  script:
    - cd packages
    - helm version
    - helm package ingress-nginx/ --version "${VERSION}" --app-version "${VERSION}"
    - curl -u "${NEXUS_REPO_USER}":"${NEXUS_REPO_PASS}" "${NEXUS_HELM_REPO}"
      --upload-file ingress-nginx-"${VERSION}".tgz

################   MAIN CI JOBS   ################

momo-store upload:
  stage: upload
  when: manual
  extends:
    - .prepare_env
    - .upload_momo-store
  only:
    - tags

monitoring-tools upload:
  stage: upload
  when: manual
  extends:
    - .prepare_env
    - .upload_monitoring-tools

cert-manager upload:
  stage: upload
  when: manual
  extends:
    - .prepare_env
    - .upload_cert-manager

ingress-nginx upload:
  stage: upload
  when: manual
  extends:
    - .prepare_env
    - .upload_ingress-nginx
